/* Query 1 - What were the most-rented film categories by month? */
WITH monthly_category_rentals AS (
    SELECT DATE_PART('month', rental.rental_date) AS rental_month_num,
        TO_CHAR(rental.rental_date, 'FMMonth') AS rental_month,
        category.name AS category_name,
        COUNT(rental.inventory_id) rental_count
    FROM rental
        LEFT JOIN inventory ON rental.inventory_id = inventory.inventory_id
        LEFT JOIN film_category ON inventory.film_id = film_category.film_id
        LEFT JOIN category ON film_category.category_id = category.category_id
    GROUP BY rental_month_num,
        rental_month,
        category_name
),
monthly_category_rentals_ranked AS (
    SELECT rental_month_num,
        rental_month,
        category_name,
        rental_count,
        RANK() OVER (
            PARTITION BY rental_month
            ORDER BY rental_count DESC
        ) as category_rank
    FROM monthly_category_rentals
)
SELECT rental_month,
    category_name
FROM monthly_category_rentals_ranked
WHERE category_rank = 1
ORDER BY rental_month_num;

/* Query 2 - What percentage of total revenue is generated by each film category? */
WITH category_revenue AS (
    SELECT category.name AS category_name,
        SUM(amount) AS amount_by_category
    FROM rental
        LEFT JOIN inventory ON rental.inventory_id = inventory.inventory_id
        LEFT JOIN film_category ON inventory.film_id = film_category.film_id
        LEFT JOIN category ON film_category.category_id = category.category_id
        LEFT JOIN payment ON rental.rental_id = payment.rental_id
    GROUP BY category.name
)
SELECT category_revenue.category_name,
    category_revenue.amount_by_category / SUM(category_revenue.amount_by_category) OVER () * 100 AS percent_revenue
FROM category_revenue;

/* Query 3 - What percentage of rentals are in each language by store? */
WITH rental_language AS (
    SELECT rental.rental_id,
        inventory.store_id,
        language.name as language_name
    FROM rental
        LEFT JOIN inventory ON rental.inventory_id = inventory.inventory_id
        LEFT JOIN film ON inventory.film_id = film.film_id
        LEFT JOIN language ON film.language_id = language.language_id
)
SELECT DISTINCT store_id,
    language_name,
    (
        COUNT(rental_id) OVER (PARTITION BY store_id, language_name)
    ) / (COUNT(rental_id) OVER (PARTITION BY store_id)) * 100 AS language_percentage
FROM rental_language
ORDER BY store_id;

/* Query 4 - Who are the top 10 most popular actors by number of rentals? */
SELECT actor.first_name || ' ' || actor.last_name as actor_name,
    COUNT(rental_id) AS film_rentals
FROM rental
    LEFT JOIN inventory ON rental.inventory_id = inventory.inventory_id
    LEFT JOIN film ON inventory.film_id = film.film_id
    INNER JOIN film_actor ON film.film_id = film_actor.film_id
    INNER JOIN actor ON film_actor.actor_id = actor.actor_id
GROUP BY actor_name
ORDER BY film_rentals DESC
LIMIT 10;
